# This is a basic workflow to help you get started with Actions

name: Build-Container-Alpine-Apache

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set environment Variables
        shell: bash
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" | tee $GITHUB_ENV
          echo "CONTAINER_NAME='alpine-apache-wordpress'" | tee $GITHUB_ENV

      #https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials for use by other steps
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Container
        working-directory: Wordpress/apache
        run: docker build -t ${process.env.CONTAINER_NAME} .

      - name: Docker tag
        run:  docker tag ${process.env.CONTAINER_NAME}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$${process.env.CONTAINER_NAME}:${process.env.BRANCH}

      - name: Push to ECR
        run:  docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${process.env.CONTAINER_NAME}:${process.env.BRANCH}
        